Debug information for folders

diff --git a/acir_tests/Dockerfile b/acir_tests/Dockerfile
--- a/acir_tests/Dockerfile
+++ b/acir_tests/Dockerfile
@@ -1,12 +1,15 @@
-FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/barretenberg-x86_64-linux-clang-assert
-FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/bb.js
+FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/barretenberg-x86_64-linux-clang-assert as builder1
+RUN test -d /usr/src/barretenberg/cpp/build || (echo "/usr/src/barretenberg/cpp/build directory not found" && exit 1)
+
+FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/bb.js as builder2
+RUN test -d /usr/src/barretenberg/ts || (echo "/usr/src/barretenberg/ts directory not found" && exit 1)
 
 FROM node:18-alpine
 
 RUN apk add --update cmake
 RUN apk update && apk add git bash curl
-COPY --from=0 /usr/src/barretenberg/cpp/build /usr/src/barretenberg/cpp/build
-COPY --from=1 /usr/src/barretenberg/ts /usr/src/barretenberg/ts
+COPY --from=builder1 /usr/src/barretenberg/cpp/build /usr/src/barretenberg/cpp/build
+COPY --from=builder2 /usr/src/barretenberg/ts /usr/src/barretenberg/ts
 WORKDIR /usr/src/barretenberg/acir_tests
 COPY . .
 # Run all native tests.
